apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: audit-authorizationpolicy
spec:
  values:
    telemetry:
      v2:
        stackdriver:
          configOverride:
            enable_audit_log: true
