apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ca-migration-meshca
spec:
  values:
    pilot:
      env:
        ENABLE_CA_SERVER: false
        ISTIO_MULTIROOT_MESH: true
  meshConfig:
    defaultConfig:
      proxyMetadata:
        PROXY_CONFIG_XDS_AGENT: "true"
    trustDomainAliases: # kpt-set: ${setters.anthos.servicemesh.trustDomainAliases}
      - "cluster.local"
