apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: citadel-ca
spec:
  components:
    pilot:
      k8s:
        env:
          - name: SPIFFE_BUNDLE_ENDPOINTS
            value: ""
          - name: TOKEN_AUDIENCES
            value: "istio-ca,PROJECT_ID.svc.id.goog" # kpt-set: istio-ca,${gcloud.core.project}.svc.id.goog
          - name: ENABLE_STACKDRIVER_MONITORING
            value: "true" # kpt-set: ${anthos.servicemesh.controlplane.monitoring.enabled}
  meshConfig:
    trustDomain: "cluster.local"
    defaultConfig:
      proxyMetadata:
        CA_PROVIDER: "Citadel"
        PLUGINS: ""
  values:
    global:
      caAddress: ""
      pilotCertProvider: "istiod"
