apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cloud-tracing
spec:
  meshConfig:
    enableTracing: true
  values:
    global:
      proxy:
        tracer: stackdriver
        # [END docs]
# [END docs]
