apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cni-onprem
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      cniBinDir: /opt/cni/bin
      excludeNamespaces:
        - istio-system
        - kube-system
        - gke-system
        # [END docs]
# [END docs]
