apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cni-selinux
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        overlays:
          - kind: DaemonSet
            name: istio-cni-node
            patches:
              - path: spec.template.spec.containers.[name:install-cni].securityContext
                value: {"privileged": true}
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
        - istio-system
        - kube-system
        # [END docs]
# [END docs]
