apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: private-ca
spec:
  components:
    pilot:
      k8s:
        env:
          - name: TOKEN_AUDIENCES
            value: "istio-ca,PROJECT_ID.svc.id.goog" # kpt-set: istio-ca,${gcloud.core.project}.svc.id.goog
          - name: EXTERNAL_CA
            value: "ISTIOD_RA_CAS_API"
          - name: CA_NAME
            value: "" # kpt-set: ${anthos.servicemesh.external_ca.ca_name}
  meshConfig:
    defaultConfig:
      proxyMetadata:
        CA_PROVIDER: "Citadel"
        PLUGINS: ""
  values:
    global:
      caAddress: ""
