apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: prometheus
spec:
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true
        stackdriver:
          enabled: false
